/**
 * @file stmt.h
 * @brief Statement AST nodes for the Vora language.
 *
 * Defines the abstract base class Stmt and all 17 concrete statement node types
 * used in the Vora AST. Each statement node inherits from Stmt and implements
 * the templated StmtVisitor<R> dispatch mechanism via two accept() overloads
 * (void for side-effecting passes, std::string for the AST printer).
 *
 * The statement hierarchy:
 *   Stmt (abstract base)
 *   +-- ExprStmt       — expression used as a statement
 *   +-- LetStmt        — variable/constant declaration (let/const)
 *   +-- BlockStmt      — braced block { ... }
 *   +-- ReturnStmt     — return value from function
 *   +-- IfStmt         — if/else conditional
 *   +-- WhileStmt      — while loop
 *   +-- DoWhileStmt    — do-while loop
 *   +-- ForStmt        — for-in loop over iterables
 *   +-- CForStmt       — C-style for (init; cond; incr)
 *   +-- FuncStmt       — function declaration
 *   +-- ObjStmt        — object/class definition
 *   +-- BreakStmt      — break out of loop
 *   +-- ContinueStmt   — continue to next loop iteration
 *   +-- ThrowStmt      — throw an exception
 *   +-- TryStmt        — try/catch/finally block
 *   +-- ImportStmt     — import module / from-import
 *   +-- ExportStmt     — export declaration
 *   +-- ErrorStmt      — placeholder for parse errors (error-tolerant parsing)
 *   +-- DeferStmt      — defer expression to function exit
 */

#pragma once

#include <memory>
#include <string>
#include <vector>

#include "expr.h"
#include "param_decl.h"
#include "binding_pattern.h"

namespace vora {

/// @brief Visitor interface for traversing statement AST nodes.
///
/// StmtVisitor<R> is templated on the return type R so that a single
/// interface definition serves all passes (e.g. void for side-effectful
/// compilation, std::string for pretty-printing).
///
/// @tparam R  The return type of the visit methods.
template <typename R>
class StmtVisitor;

/**
 * @brief Abstract base class for all statement AST nodes.
 *
 * Every concrete statement type inherits from Stmt and implements the visitor
 * dispatch via two accept() overloads (one for void-returning visitors like the
 * compiler, one for std::string-returning visitors like the AST printer).
 * When adding a new visitor pass with a new return type R, add a new
 * pure-virtual accept() overload here and implement it in each subclass.
 */
class Stmt {
public:
    virtual ~Stmt() = default;

    // One accept() overload per return type in use. When adding a new pass
    // with a new R, add a new pure-virtual overload here and implement it
    // in each concrete subclass (stmt.cpp).
    virtual void         accept(StmtVisitor<void>& visitor)         const = 0;
    virtual std::string  accept(StmtVisitor<std::string>& visitor)  const = 0;
};

/**
 * @brief An expression used in statement position.
 *
 * Wraps a single expression (e.g. a function call, assignment, or literal)
 * so it can appear where a statement is expected. The expression's value is
 * discarded after evaluation. Generated by the parser from expression
 * statements terminated by a semicolon or newline.
 */
class ExprStmt : public Stmt {
public:
    explicit ExprStmt(
        std::unique_ptr<Expr> expression
    )
        : expression(std::move(expression)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> expression;  ///< The expression to evaluate.
};

/**
 * @brief Variable or constant declaration (`let` / `const`).
 *
 * Represents a variable binding with an optional initializer expression.
 * Supports optional type annotations (`let x: number = 5`), the `const`
 * keyword for immutable bindings, and destructuring via BindingPattern
 * (`let [a, b] = pair` or `let {x, y} = point`).
 *
 * When a BindingPattern is present, `name` is empty and the pattern
 * describes the destructuring structure. When absent, `name` holds the
 * simple variable name.
 */
class LetStmt : public Stmt {
public:
    LetStmt(
        std::string name,
        Token nameToken,
        std::unique_ptr<Expr> initializer,
        std::string typeAnnotation = "",
        bool isConst = false,
        std::unique_ptr<BindingPattern> binding = nullptr
    )
        : name(std::move(name)),
          nameToken(std::move(nameToken)),
          initializer(std::move(initializer)),
          typeAnnotation(std::move(typeAnnotation)),
          isConst(isConst),
          binding(std::move(binding)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::string name;                     ///< Variable name (empty when destructuring).

    Token nameToken;                      ///< Position of the variable name for diagnostics.

    std::unique_ptr<Expr> initializer;    ///< Initial value expression (may be nullptr).

    std::string typeAnnotation;           ///< Optional type hint string (empty = none).

    bool isConst = false;                 ///< True if declared with 'const' keyword.

    // Destructuring binding pattern (null for simple let x = y).
    // When non-null, name is empty and the binding describes the
    // array/object destructuring pattern.
    std::unique_ptr<BindingPattern> binding;  ///< Destructuring pattern (nullptr = simple binding).
};

/**
 * @brief A braced block of statements `{ ... }`.
 *
 * Groups a sequence of statements into a single compound statement.
 * Each block introduces a new lexical scope for local variables.
 * Ownership of child statements is held via unique_ptr.
 */
class BlockStmt : public Stmt {
public:
    explicit BlockStmt(
        std::vector<std::unique_ptr<Stmt>> statements
    )
        : statements(std::move(statements)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::vector<std::unique_ptr<Stmt>> statements;  ///< Statements in the block body.
};

/**
 * @brief Return statement — exits the current function with an optional value.
 *
 * In a function with no explicit return, the VM implicitly returns `null`.
 * The value may be nullptr for bare `return;` statements.
 */
class ReturnStmt : public Stmt {
public:
    explicit ReturnStmt(
        std::unique_ptr<Expr> value
    )
        : value(std::move(value)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> value;  ///< Return value expression (nullptr for bare return).
};

/**
 * @brief If/else conditional statement.
 *
 * Evaluates `condition`; if truthy, executes `thenBranch`, otherwise
 * executes `elseBranch` (which may be nullptr for if-without-else).
 * Chains of `else if` are represented by nesting: the elseBranch of one
 * IfStmt is another IfStmt.
 */
class IfStmt : public Stmt {
public:
    IfStmt(
        std::unique_ptr<Expr> condition,
        std::unique_ptr<Stmt> thenBranch,
        std::unique_ptr<Stmt> elseBranch
    )
        : condition(std::move(condition)),
          thenBranch(std::move(thenBranch)),
          elseBranch(std::move(elseBranch)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> condition;   ///< Condition expression evaluated for truthiness.

    std::unique_ptr<Stmt> thenBranch;  ///< Executed when condition is truthy.

    std::unique_ptr<Stmt> elseBranch;  ///< Executed when condition is falsy (nullptr if no else).
};

/**
 * @brief While loop statement.
 *
 * Repeatedly evaluates `condition`; if truthy, executes `body`, then
 * re-evaluates the condition. Supports `break` and `continue` within the body.
 */
class WhileStmt : public Stmt {
public:
    WhileStmt(
        std::unique_ptr<Expr> condition,
        std::unique_ptr<Stmt> body
    )
        : condition(std::move(condition)),
          body(std::move(body)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> condition;  ///< Loop condition expression (checked before each iteration).

    std::unique_ptr<Stmt> body;       ///< Loop body executed while condition is truthy.
};

/**
 * @brief Do-while loop statement.
 *
 * Executes `body` once unconditionally, then repeatedly evaluates `condition`;
 * if truthy, loops back to execute `body` again. Guarantees at least one
 * iteration of the body. Supports `break` and `continue` within the body.
 */
class DoWhileStmt : public Stmt {
public:
    DoWhileStmt(
        std::unique_ptr<Expr> condition,
        std::unique_ptr<Stmt> body
    )
        : condition(std::move(condition)),
          body(std::move(body)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> condition;  ///< Loop condition (checked after each iteration).

    std::unique_ptr<Stmt> body;       ///< Loop body executed at least once.
};

/**
 * @brief For-in loop statement (`for (x in iterable) body`).
 *
 * Iterates over each element of an iterable value (array, string, etc.).
 * The loop variable `variable` is bound to each element in sequence.
 * Desugared by the compiler into a while loop using internal iterator locals.
 * Supports `break` and `continue` within the body.
 */
class ForStmt : public Stmt {
public:
    ForStmt(
        std::string variable,
        std::unique_ptr<Expr> iterable,
        std::unique_ptr<Stmt> body,
        Token forToken
    )
        : variable(std::move(variable)),
          iterable(std::move(iterable)),
          body(std::move(body)),
          forToken(std::move(forToken)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::string variable;                ///< Loop variable name bound to each element.

    std::unique_ptr<Expr> iterable;      ///< Expression producing the collection to iterate.

    std::unique_ptr<Stmt> body;          ///< Loop body executed for each element.

    Token forToken;                      ///< 'for' keyword token for error location.
};

/**
 * @brief C-style for loop (`for (init; cond; incr) body`).
 *
 * Classic three-clause for loop:
 * - `initializer`: executed once before the loop (let stmt, expr stmt, or nullptr).
 * - `condition`: evaluated before each iteration (nullptr = always true).
 * - `increment`: executed after each iteration (nullptr = no increment).
 *
 * All three clauses are optional; `for (;;)` is an infinite loop.
 * Supports `break` and `continue` within the body.
 */
class CForStmt : public Stmt {
public:
    CForStmt(
        std::unique_ptr<Stmt> initializer,
        std::unique_ptr<Expr> condition,
        std::unique_ptr<Expr> increment,
        std::unique_ptr<Stmt> body
    )
        : initializer(std::move(initializer)),
          condition(std::move(condition)),
          increment(std::move(increment)),
          body(std::move(body)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Stmt> initializer;  ///< Initializer clause: let stmt, expr stmt, or nullptr.
    std::unique_ptr<Expr> condition;    ///< Loop condition (nullptr = always true).
    std::unique_ptr<Expr> increment;    ///< Increment expression (nullptr = no increment).
    std::unique_ptr<Stmt> body;         ///< Loop body.
};

/**
 * @brief Function declaration statement.
 *
 * Declares a named function with parameters and a body. The body is stored
 * as shared_ptr<BlockStmt> to support closure capture. When compiled, the
 * function body becomes a FunctionPrototype in the constant pool, and
 * OP_CLOSURE creates a VoraFunction at runtime.
 *
 * When isStatic is true, the function was declared with `this.func` syntax
 * inside an Obj and is treated as a static method.
 */
class FuncStmt : public Stmt {
public:
    /// @brief Construct a FuncStmt.
    /// @param name       The function name.
    /// @param nameToken  Source position of the function name.
    /// @param params     The parameter declarations.
    /// @param body       The function body block (shared ownership for closure capture).
    /// @param isStatic   True if declared with 'this.func' syntax inside Obj.
    FuncStmt(
        std::string name,
        Token nameToken,
        std::vector<ParamDecl> params,
        std::shared_ptr<BlockStmt> body,
        bool isStatic = false,
        bool isAsync = false
    )
        : name(std::move(name)),
          nameToken(std::move(nameToken)),
          params(std::move(params)),
          body(std::move(body)),
          isStatic(isStatic),
          isAsync(isAsync) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::string name;                    ///< The function name.

    Token nameToken;                     ///< position of the function name

    std::vector<ParamDecl> params;       ///< The parameter declarations.

    std::shared_ptr<BlockStmt> body;     ///< The function body block.

    bool isStatic = false;               ///< true if declared with 'this.func' inside Obj
    bool isAsync = false;                ///< true if declared with 'async' keyword
};

/**
 * @brief Object/class definition statement.
 *
 * Declares a class with optional parent inheritance, constructor parameters,
 * methods, and an initialization body. Uses C3 linearization (MRO) for
 * multiple inheritance resolution.
 *
 * At compile time, the constructor body and methods are compiled into
 * separate FunctionPrototypes and wrapped in a ClassDefinition stored in
 * the constant pool. OP_CLASS resolves parent references and computes the
 * MRO at runtime.
 */
class ObjStmt : public Stmt {
public:
    /// @brief Construct an ObjStmt.
    /// @param name         The class name.
    /// @param nameToken    Source position of the class name.
    /// @param parentNames  Parent class names (empty = no inheritance).
    /// @param params       Constructor parameter declarations.
    /// @param methods      Method statements (FuncStmt nodes extracted during parsing).
    /// @param body         Constructor body block (shared ownership).
    ObjStmt(
        std::string name,
        Token nameToken,
        std::vector<std::string> parentNames,
        std::vector<ParamDecl> params,
        std::vector<std::unique_ptr<Stmt>> methods,
        std::shared_ptr<BlockStmt> body
    )
        : name(std::move(name)),
          nameToken(std::move(nameToken)),
          parentNames(std::move(parentNames)),
          params(std::move(params)),
          methods(std::move(methods)),
          body(std::move(body)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::string name;                          ///< The class name.

    Token nameToken;                           ///< position of the class name

    std::vector<std::string> parentNames;      ///< empty = no inheritance

    std::vector<ParamDecl> params;             ///< Constructor parameter declarations.

    std::vector<std::unique_ptr<Stmt>> methods; ///< Method statements (FuncStmt nodes).

    std::shared_ptr<BlockStmt> body;           ///< Constructor body block.
};

/**
 * @brief Break statement — exits the nearest enclosing loop.
 *
 * Only valid inside while, do-while, for-in, C-style for loops, and
 * match expressions. The compiler resolves the break target by walking
 * the loop stack and back-patching jump offsets.
 */
class BreakStmt : public Stmt {
public:
    /// @brief Construct a BreakStmt.
    /// @param keyword  The 'break' token for source position.
    explicit BreakStmt(Token keyword)
        : keyword(std::move(keyword)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    Token keyword;  ///< The 'break' token for diagnostics.
};

/**
 * @brief Continue statement — skips to the next iteration of the enclosing loop.
 *
 * Only valid inside loops. Jumps to the loop's condition check (while/do-while/
 * for) or increment clause (C-style for). The compiler resolves the continue
 * target via the loop stack.
 */
class ContinueStmt : public Stmt {
public:
    /// @brief Construct a ContinueStmt.
    /// @param keyword  The 'continue' token for source position.
    explicit ContinueStmt(Token keyword)
        : keyword(std::move(keyword)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    Token keyword;  ///< The 'continue' token for diagnostics.
};

/**
 * @brief Throw statement — raises an exception with a value.
 *
 * The exception value propagates up the call stack until caught by a
 * try/catch handler, or reaches the top level where it causes a runtime
 * error. Any value type can be thrown.
 */
class ThrowStmt : public Stmt {
public:
    /// @brief Construct a ThrowStmt.
    /// @param value    The exception value expression.
    /// @param keyword  The 'throw' token for source position.
    explicit ThrowStmt(
        std::unique_ptr<Expr> value,
        Token keyword
    )
        : value(std::move(value)),
          keyword(std::move(keyword)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> value;  ///< The exception value expression.

    Token keyword;                 ///< The 'throw' token for diagnostics.
};

/**
 * @brief Try/catch/finally statement for structured exception handling.
 *
 * Executes the try block. If an exception is thrown, the catch block (if
 * present) receives the exception value bound to catchVar. The finally
 * block (if present) always executes, regardless of exceptions or returns.
 *
 * At least one of catchBlock or finallyBlock must be present.
 * The compiler emits OP_PUSH_CATCH/OP_POP_CATCH for handler registration
 * and OP_FINALLY_END for finally propagation logic.
 */
class TryStmt : public Stmt {
public:
    /// @brief Construct a TryStmt.
    /// @param tryBlock     The protected body.
    /// @param catchVar     Variable name for caught exception (empty = no catch).
    /// @param catchBlock   The catch handler body (nullptr if no catch).
    /// @param finallyBlock The always-executed body (nullptr if no finally).
    TryStmt(
        std::unique_ptr<Stmt> tryBlock,
        std::string catchVar,
        std::unique_ptr<Stmt> catchBlock,
        std::unique_ptr<Stmt> finallyBlock
    )
        : tryBlock(std::move(tryBlock)),
          catchVar(std::move(catchVar)),
          catchBlock(std::move(catchBlock)),
          finallyBlock(std::move(finallyBlock)) {
    }

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Stmt> tryBlock;      ///< The protected body.

    std::string catchVar;                ///< empty = no catch clause

    std::unique_ptr<Stmt> catchBlock;    ///< nullptr if no catch

    std::unique_ptr<Stmt> finallyBlock;  ///< nullptr if no finally
};

/**
 * @brief Import statement for loading external modules.
 *
 * Supports two forms:
 * - `import "path"` — auto-binds a module variable named after the path
 *   basename (without .va extension), or uses an optional `as` alias.
 * - `from "path" import a, b, c` — imports specific names directly into
 *   scope. When importNames is non-empty, no module variable is created;
 *   each name is extracted from the module dict and bound individually.
 */
// import "path" — statement that auto-binds a module variable (Python 3 style).
// The variable name is derived from the path basename (without .va extension),
// or from the optional `as` alias: `import "math" as M` binds variable `M`.
//
// from "path" import a, b, c — imports specific names directly into scope.
// When importNames is non-empty, no module variable is created; each name
// in importNames is extracted from the module dict and bound individually.
class ImportStmt : public Stmt {
public:
    /// @brief Construct an ImportStmt.
    /// @param modulePath   Raw path string from source.
    /// @param keyword      'import' or 'from' token (for error location).
    /// @param alias        Optional 'as' alias (empty = derive from basename).
    /// @param importNames  Non-empty for "from...import" form.
    ImportStmt(std::string modulePath, Token keyword, std::string alias = "",
               std::vector<std::string> importNames = {})
        : modulePath(std::move(modulePath)), keyword(std::move(keyword)),
          alias(std::move(alias)), importNames(std::move(importNames)) {}

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::string modulePath;                         ///< raw path string from source

    Token keyword;                                   ///< 'import' or 'from' token (for error location)

    std::string alias;                               ///< optional 'as' alias name (empty = derive from basename)

    std::vector<std::string> importNames;            ///< non-empty = "from...import" form
};

/**
 * @brief Export declaration — marks a declaration as publicly visible.
 *
 * Wraps a FuncStmt, LetStmt, or ObjStmt. Exported declarations are
 * accessible to other modules via import. Const declarations use
 * LetStmt with isConst=true.
 */
// export <declaration> — marks a declaration as publicly visible.
// Wraps a FuncStmt, LetStmt, ConstStmt, or ObjStmt.
class ExportStmt : public Stmt {
public:
    /// @brief Construct an ExportStmt.
    /// @param declaration  The declaration to export (FuncStmt / LetStmt / ObjStmt).
    /// @param keyword      The 'export' token for source position.
    ExportStmt(std::unique_ptr<Stmt> declaration, Token keyword)
        : declaration(std::move(declaration)), keyword(std::move(keyword)) {}

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Stmt> declaration;  ///< FuncStmt / LetStmt / ObjStmt (const uses LetStmt.isConst)

    Token keyword;                       ///< 'export' token
};

/**
 * @brief Placeholder for a parse error in statement context.
 *
 * Used by error-tolerant parsing to retain partial AST structure.
 * Visitors that execute code should treat it as a no-op.
 */
// ErrorStmt — placeholder for a parse error in statement context.
// Used by error-tolerant parsing to retain partial AST structure.
// Visitors that execute code should treat it as a no-op.
class ErrorStmt : public Stmt {
public:
    /// @brief Construct an ErrorStmt.
    /// @param message     The error message.
    /// @param errorToken  The token where the error occurred.
    ErrorStmt(std::string message, Token errorToken)
        : message(std::move(message)), errorToken(std::move(errorToken)) {}

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::string message;   ///< The error message.

    Token errorToken;      ///< Source position of the error.
};

/**
 * @brief Defer statement — schedules an expression to execute at function exit.
 *
 * `defer <expr>;` registers a deferred expression that executes when the
 * enclosing function returns, regardless of how it returns (normal, return,
 * or exception). Multiple deferred expressions execute in LIFO order
 * (last deferred, first executed).
 */
// DeferStmt — schedules an expression to execute at function exit.
// defer <expr>;
// Deferred expressions execute in LIFO order when the function returns.
class DeferStmt : public Stmt {
public:
    /// @brief Construct a DeferStmt.
    /// @param expression  The expression to defer.
    /// @param keyword     The 'defer' token for source position.
    DeferStmt(std::unique_ptr<Expr> expression, Token keyword)
        : expression(std::move(expression)), keyword(std::move(keyword)) {}

    void        accept(StmtVisitor<void>& visitor)        const override;
    std::string accept(StmtVisitor<std::string>& visitor) const override;

    std::unique_ptr<Expr> expression;  ///< The deferred expression.

    Token keyword;                      ///< The 'defer' token for diagnostics.
};

}
