print("=== array ===")
for item in [10, 20, 30] {
    print(item)
}
print("=== string ===")
for ch in "Vora" {
    print(ch)
}
print("=== range(5) ===")
for i in range(5) {
    print(i)
}
print("=== range(2, 6) ===")
for i in range(2, 6) {
    print(i)
}
print("=== range(5, 0, -1) ===")
for i in range(5, 0, -1) {
    print(i)
}
print("===")
for i in range(10) {
    if (i == 2) {
        continue
    }
    if (i == 5) {
        break
    }
    print(i)
}
