#!/usr/bin/env python3
"""
extract-builtins.py — 从 builtins.cpp 提取内建函数签名，生成 Markdown 表格

Usage:
    python scripts/extract-builtins.py

Reads src/runtime/builtins.cpp, finds all vm.defineNative() calls,
and outputs a Markdown table of all builtin functions grouped by category.

This table can be inserted into USER_GUIDE.md's "内建函数" section.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUILTINS_CPP = REPO_ROOT / "src" / "runtime" / "builtins.cpp"


def extract_builtins(source: str) -> list[dict]:
    """
    Extract builtin function definitions from builtins.cpp.

    Pattern:
        vm.defineNative("name", arity, [](args) -> Value { ... });

    Returns list of dicts with keys: name, arity, description, category
    """
    # Find all defineNative calls
    pattern = re.compile(
        r'vm\.defineNative\(\s*"([^"]+)"\s*,\s*(-?\d+)\s*,',
        re.MULTILINE
    )

    builtins = []
    for m in pattern.finditer(source):
        name = m.group(1)
        arity = m.group(2)
        # Extract the comment preceding the defineNative call (if any)
        pos = m.start()
        # Look backwards for a /// comment
        prev_text = source[max(0, pos - 500):pos]
        desc = ""
        for line in reversed(prev_text.split("\n")):
            line_stripped = line.strip()
            if line_stripped.startswith("///"):
                desc = line_stripped[3:].strip()
                break

        builtins.append({
            "name": name,
            "arity": arity,
            "description": desc,
        })

    return builtins


def arity_display(arity: str) -> str:
    """Convert arity number to display string."""
    a = int(arity)
    if a == -1:
        return "variadic"
    return str(a)


def categorize(name: str) -> str:
    """Assign a category to a builtin function."""
    categories = {
        "print": "输出",
        "type": "类型",
        "int": "类型",
        "float": "类型",
        "toString": "类型",
        "len": "工具",
        "clock": "工具",
        "assert": "工具",
        "input": "工具",
        "range": "工具",
        "bin": "进制",
        "oct": "进制",
        "hex": "进制",
        "iter": "迭代器",
        "next": "迭代器",
        "abs": "数学",
        "sqrt": "数学",
        "sin": "数学",
        "cos": "数学",
        "min": "数学",
        "max": "数学",
        "random_int": "数学",
        "random_float": "数学",
        "jsonParse": "JSON",
        "jsonStringify": "JSON",
        "_vora_len": "内部",
    }
    return categories.get(name, "其他")


def main():
    if not BUILTINS_CPP.exists():
        print(f"ERROR: {BUILTINS_CPP} not found", file=sys.stderr)
        sys.exit(1)

    source = BUILTINS_CPP.read_text(encoding="utf-8")
    builtins = extract_builtins(source)

    if not builtins:
        print("ERROR: No builtins found", file=sys.stderr)
        sys.exit(1)

    # Group by category
    by_category: dict[str, list[dict]] = {}
    for b in builtins:
        cat = categorize(b["name"])
        if cat == "内部":
            continue  # skip internal builtins
        by_category.setdefault(cat, []).append(b)

    # Output Markdown table
    print("<!-- AUTO-GENERATED by scripts/extract-builtins.py -->")
    print("<!-- DO NOT EDIT MANUALLY — edit builtins.cpp and re-run -->")
    print()

    for cat in ["输出", "类型", "工具", "迭代器", "数学", "进制", "JSON", "其他"]:
        if cat not in by_category:
            continue
        items = by_category[cat]
        print(f"### {cat} / {cat}")
        print()
        print("| 函数 / Function | 参数 / Arity | 说明 / Description |")
        print("|----------------|-------------|-------------------|")
        for b in items:
            arity = arity_display(b["arity"])
            desc = b["description"] if b["description"] else "-"
            print(f"| `{b['name']}` | {arity} | {desc} |")
        print()


if __name__ == "__main__":
    main()
